name: Aliveland Subgraph Deployment

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: yarn --frozen-lockfile
      - id: install-graph-cli
        run: |
          yarn global add @graphprotocol/graph-cli@0.60.0
          echo "$(yarn global bin)" >> $GITHUB_PATH
        shell: bash
      - name: Codegen
        run: graph codegen
      - name: Build
        run: graph build
      - name: Deploy
        run: graph deploy --product hosted-service --access-token ${{secrets.graph_access_token}} --node https://api.thegraph.com/deploy/ cdreamer1/aliveland-nft-subgraph